---
- name: Using the IBM Spectrum Virtualize collection
  hosts: localhost
  vars_files:
   - ../vars/main.yml
  tasks:
    - name: Gather info from storage
      ibm.spectrum_virtualize.ibm_svc_info:
        clustername: "{{ StorageIP }}"
        domain:
        username: "{{ user }}"
        password: "{{ pass }}"
        gather_subset: rcrelationship
      register: "rcresults"  
    - local_action: copy content={{ rcresults }} dest={{ dummyexp }}
    - name: Python Cook 
      shell: python3 {{ pycook }} {{ dummyexp }} {{ res }}
      delegate_to: localhost
      run_once: True
    - name: Shell Cook and result
      shell: sh {{ shcook }} {{ res }} {{ output }} {{ maxtime }}
      delegate_to: localhost
      run_once: True
      #Avoid Ansible errors on zero repl problem
      ignore_errors: true 
      failed_when: false